name: android_sms_consent_example
description: Demonstrates how to use the android_sms_consent plugin.

publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_sms_consent:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
