name: android_sms_consent
description: Flutter plugin to perform one-tap SMS verification with the SMS User Consent API in Android.

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.khalti.android_sms_consent
        pluginClass: AndroidSmsConsentPlugin
